"""Initial migration.

Revision ID: 07a45ad43d02
Revises: 
Create Date: 2025-03-28 13:33:44.185618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a45ad43d02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('ip', sa.String(length=32), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.Column('alive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_name'))
        batch_op.drop_index(batch_op.f('ix_node_ip'))

    op.drop_table('node')
    # ### end Alembic commands ###
